const baseUrl = "https://mirage-products-api.herokuapp.com"
const buttonDiv = () => document.getElementById("button-control")
const buttonShow = () => document.getElementById("button-show")
const buttonNew = () => document.getElementById("button-new")
const ulDiv = () => document.getElementById("list")
const ul = () => document.getElementById("categories-list")
const productForm = () => document.getElementById("product-form")
const productName = () => document.getElementById("product-name")
const productPrice = () => document.getElementById("product-price")
const productDescription = () => document.getElementById("product-description")
const productSelectCategory = () => document.getElementById("category_id")
const categoriesSection = () => document.querySelector("#categories-section")
const flash = () => document.querySelector("#flash")